import localFont from "next/font/local";
import { ViewTransitions } from "next-view-transitions";
import Header from "@/app/components/Header";

import "./globals.scss"; 

const PPNeueMontreal = localFont({
	src: [
		{
			path: "./fonts/PPNeueMontreal/PPNeueMontreal-Bold.woff2",
			weight: "700",
			style: "normal",
		},
    {
			path: "./fonts/PPNeueMontreal/PPNeueMontreal-Medium.woff2",
			weight: "500",
			style: "normal",
		},
    {
			path: "./fonts/PPNeueMontreal/PPNeueMontreal-Book.woff2",
			weight: "400",
			style: "normal",
		},
	
	],
	variable: "--font-pp", 
});



export const metadata = {
	title: "The Clouds",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ViewTransitions>
			<html lang="en">
				<body>
					{children}
				</body>
			</html>
		</ViewTransitions>
		
	);
}
